#!/bin/bash
IFS=$'\n'
ls *.mp3 | sed 's/-[^\ ].*[^A,E,Y,U,I,O,a,e,y,u,i,o][^A,E,Y,U,I,O,a,e,y,u,i,o].*/\.mp3/' > output


new=(`cat output`)
i=0
for name in `ls $1/*.mp3` 
do
    mv $name ${new[$i]} &> /dev/null
    i=$[ $i + 1 ]
done
rm output
